import { contextBridge, ipcRenderer } from "electron";

const validChannels = [
  "getAppStatus",
  "saveInitialSetup",
  "resetSetupWizard",
  "runDoctor",
  "runRuntimePathCheck",
  "installDependencies",
  "buildMcpServer",
  "readLocalConfig",
  "saveLocalConfig",
  "selectFolder",
  "generateClientConfigs",
  "configureOAuthAdminPassword",
  "resetOAuthClients",
  "revokeAllOAuthTokens",
  "revokeChatGptOAuthTokens",
  "clearExpiredOAuthTokens",
  "openOAuthMetadata",
  "openProtectedResourceMetadata",
  "getOAuthMetadataPreview",
  "getProtectedResourceMetadataPreview",
  "copyGenericConfig",
  "openGeneratedFolder",
  "openAuditLog",
  "openLogsFolder",
  "openDocs",
  "openChatGptGuide",
  "openDomainGuide",
  "openCloudflareGuide",
  "openCloudflareDashboard",
  "openCloudflaredConfigTemplate",
  "runTunnelReadinessCheck",
  "openLocalHealthCheck",
  "copyLocalMcpEndpoint",
  "copyPublicMcpEndpoint",
  "copyPublicHealthEndpoint",
  "setHttpWriteToolsEnabled",
  "setWriteMode",
  "clearPendingPatchProposals",
  "getWriteAccessStatus",
  "getFigmaStatus",
  "saveFigmaAccessToken",
  "clearFigmaAccessToken",
  "parseFigmaUrl",
  "testFigmaConnection",
  "createFigmaHandoffPackage",
  "createCodexUiHandoffPrompt",
  "saveWriteApprovalToken",
  "clearWriteApprovalToken",
  "generateWriteApprovalToken",
  "copyTemporaryWriteToken",
  "getHttpAuthStatus",
  "saveHttpAuthToken",
  "clearHttpAuthToken",
  "generateHttpAuthToken",
  "setUnauthenticatedLocalHttpAllowed",
  "startDiagnosticServer",
  "stopDiagnosticServer",
  "getDiagnosticServerStatus"
] as const;

type Channel = (typeof validChannels)[number];

function invoke<T>(channel: Channel, ...args: unknown[]): Promise<T> {
  return ipcRenderer.invoke(channel, ...args) as Promise<T>;
}

contextBridge.exposeInMainWorld("champcity", {
  getAppStatus: () => invoke("getAppStatus"),
  saveInitialSetup: (payload: unknown) => invoke("saveInitialSetup", payload),
  resetSetupWizard: () => invoke("resetSetupWizard"),
  runDoctor: () => invoke("runDoctor"),
  runRuntimePathCheck: () => invoke("runRuntimePathCheck"),
  installDependencies: () => invoke("installDependencies"),
  buildMcpServer: () => invoke("buildMcpServer"),
  readLocalConfig: () => invoke("readLocalConfig"),
  saveLocalConfig: (config: unknown, confirmedOutsideProjects = false) =>
    invoke("saveLocalConfig", { config, confirmedOutsideProjects }),
  selectFolder: () => invoke("selectFolder"),
  generateClientConfigs: () => invoke("generateClientConfigs"),
  configureOAuthAdminPassword: (password: string) => invoke("configureOAuthAdminPassword", password),
  resetOAuthClients: () => invoke("resetOAuthClients"),
  revokeAllOAuthTokens: () => invoke("revokeAllOAuthTokens"),
  revokeChatGptOAuthTokens: () => invoke("revokeChatGptOAuthTokens"),
  clearExpiredOAuthTokens: () => invoke("clearExpiredOAuthTokens"),
  openOAuthMetadata: () => invoke("openOAuthMetadata"),
  openProtectedResourceMetadata: () => invoke("openProtectedResourceMetadata"),
  getOAuthMetadataPreview: () => invoke("getOAuthMetadataPreview"),
  getProtectedResourceMetadataPreview: () => invoke("getProtectedResourceMetadataPreview"),
  copyGenericConfig: () => invoke("copyGenericConfig"),
  openGeneratedFolder: () => invoke("openGeneratedFolder"),
  openAuditLog: () => invoke("openAuditLog"),
  openLogsFolder: () => invoke("openLogsFolder"),
  openDocs: () => invoke("openDocs"),
  openChatGptGuide: () => invoke("openChatGptGuide"),
  openDomainGuide: () => invoke("openDomainGuide"),
  openCloudflareGuide: () => invoke("openCloudflareGuide"),
  openCloudflareDashboard: () => invoke("openCloudflareDashboard"),
  openCloudflaredConfigTemplate: () => invoke("openCloudflaredConfigTemplate"),
  runTunnelReadinessCheck: () => invoke("runTunnelReadinessCheck"),
  openLocalHealthCheck: () => invoke("openLocalHealthCheck"),
  copyLocalMcpEndpoint: () => invoke("copyLocalMcpEndpoint"),
  copyPublicMcpEndpoint: () => invoke("copyPublicMcpEndpoint"),
  copyPublicHealthEndpoint: () => invoke("copyPublicHealthEndpoint"),
  setHttpWriteToolsEnabled: (enabled: boolean) => invoke("setHttpWriteToolsEnabled", enabled),
  setWriteMode: (writeMode: "off" | "docs" | "patch" | "elevated") => invoke("setWriteMode", writeMode),
  clearPendingPatchProposals: () => invoke("clearPendingPatchProposals"),
  getWriteAccessStatus: () => invoke("getWriteAccessStatus"),
  getFigmaStatus: () => invoke("getFigmaStatus"),
  saveFigmaAccessToken: (token: string) => invoke("saveFigmaAccessToken", token),
  clearFigmaAccessToken: () => invoke("clearFigmaAccessToken"),
  parseFigmaUrl: (url: string) => invoke("parseFigmaUrl", url),
  testFigmaConnection: (figmaUrlOrFileKey: string) => invoke("testFigmaConnection", { figmaUrlOrFileKey }),
  createFigmaHandoffPackage: (payload: unknown) => invoke("createFigmaHandoffPackage", payload),
  createCodexUiHandoffPrompt: (payload: unknown) => invoke("createCodexUiHandoffPrompt", payload),
  saveWriteApprovalToken: (token: string) => invoke("saveWriteApprovalToken", token),
  clearWriteApprovalToken: () => invoke("clearWriteApprovalToken"),
  generateWriteApprovalToken: () => invoke("generateWriteApprovalToken"),
  copyTemporaryWriteToken: (token: string) => invoke("copyTemporaryWriteToken", token),
  getHttpAuthStatus: () => invoke("getHttpAuthStatus"),
  saveHttpAuthToken: (token: string) => invoke("saveHttpAuthToken", token),
  clearHttpAuthToken: () => invoke("clearHttpAuthToken"),
  generateHttpAuthToken: () => invoke("generateHttpAuthToken"),
  setUnauthenticatedLocalHttpAllowed: (enabled: boolean) => invoke("setUnauthenticatedLocalHttpAllowed", enabled),
  startDiagnosticServer: () => invoke("startDiagnosticServer"),
  stopDiagnosticServer: () => invoke("stopDiagnosticServer"),
  getDiagnosticServerStatus: () => invoke("getDiagnosticServerStatus"),
  onLog: (callback: (line: string) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, line: string) => callback(line);
    ipcRenderer.on("launcher:log", listener);
    return () => ipcRenderer.removeListener("launcher:log", listener);
  }
});
